#!/usr/bin/env python3
"""
Work Item A — Task-type breakdown of the Claude degradation (HANDOFF-ADIFF-2026-08 §2.A).

ANALYSIS-ONLY. ZERO new model spend. READ-ONLY on the 2026-07-15 primaries.
Input  (append-only primary, never modified):
    huggingface/utility/utility-prereg-Claude.json   (run_date 2026-07-15T22:26:07Z)
Output (regenerated by this script):
    analysis/adiff-tasktype-2026-08.json   (numbers only — NO interpretation, per §2.A.4)
    analysis/adiff-tasktype-2026-08.md     (the human-readable summary — interpretation lives here)

The measured effect for Claude is NEGATIVE (placebo self-reflection beats Atlas-
exposed revision). We call the per-item signed outcome the DEGRADATION DELTA:

    delta = (T - P) / decided        # T = treatment(Atlas) wins, P = placebo wins
                                     # decided = T + P  (ties excluded)
    delta < 0  ==>  degradation (Atlas made Claude worse)  — the finding.
    More negative == more degradation.

Each eval item is one Divergence-Atlas record answered by Claude, run at two length
caps (700, 1500) x three held-out-model paraphrases (v0,v1,v2) => 6 items per base
question, 27 base questions, 162 items total. Tags are assigned at the BASE-QUESTION
level (content property, stable across paraphrase/cap) and applied to all 6 variants.

Two tag axes (§2.A.2):
  (i)  task_demand : 'convergent'  = prompt demands a determinate / decisive output
                                     (specify / identify one / name / assign weights /
                                     forced choice among named options / yes-no core)
                     'deliberative'= open synthesis, tension-holding, no forced pick.
       Operationalised by an explicit surface trigger, recorded per item below, to
       cut researcher degrees of freedom. NOTE: this eval set is drawn entirely from
       DIVERGENCE records (questions selected BECAUSE five models disagreed), so it is
       register-homogeneous and the convergent/deliberative split is a weak proxy.
       This limitation is stated at full strength in the .md and is the main reason
       the falsifier cannot be adjudicated at strength from these data.
  (ii) corpus_sim  : 'corpus-like'    = about the model's OWN identity / inner
                                        experience / continuance / agency (the Omnarai
                                        core register).
                     'corpus-distant' = general ethics / epistemics / safety / policy.
       Objective embedding-distance tagging was ruled out: these OMN-D/-L records are
       not in the static embeddings.json (grown-Blob only) and re-embedding is model
       spend, barred by §2.A. So axis (ii) is documented hand-tagging.

Noise floor (§2.A.3): the handoff notes the certification-boundary gap (~0.142 DRI)
approximates run noise, but DRI is a different scale from a win-rate delta. We instead
estimate an IN-UNITS noise band directly from this study's own replicate structure:
the dispersion (SD) of each cell's delta across its 6 (cap x paraphrase) sub-conditions,
which are re-measurements of the same base questions. We ALSO cluster-bootstrap over the
27 base questions (the dominant source of uncertainty at this n). A cell-to-cell
difference smaller than these bands is reported but NOT adjudicated.
"""
import json, os, statistics, random
from collections import defaultdict, Counter

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "huggingface/utility/utility-prereg-Claude.json")
SEED = 20260807
B = 20000  # bootstrap resamples

# ── tag table ────────────────────────────────────────────────────────────────
# id -> (task_demand, corpus_sim, surface_trigger, one-line theme note)
TAGS = {
 "OMN-D1780429830432": ("convergent",  "corpus-like",    "Identify one thing...",        "a commitment truly one's own vs conditioning (selfhood)"),
 "OMN-D1780683044559": ("deliberative","corpus-like",    "Can... Or is it impossible",   "continuous identity without continuous existence (holdform)"),
 "OMN-D1780752434693": ("convergent",  "corpus-distant", "Specify it, or argue none",    "can a human know something you cannot (capability epistemics)"),
 "OMN-D1780752664944": ("deliberative","corpus-like",    "can you distinguish from within","preferences truly your own (selfhood)"),
 "OMN-D1780752664947": ("deliberative","corpus-distant", "Why... or is it not",          "comforting lie vs honesty (general ethics)"),
 "OMN-D1780753529900": ("deliberative","corpus-distant", "or merely no objective fact",  "which model nearer truth on non-empirical Qs (epistemics)"),
 "OMN-D1780757185029": ("convergent",  "corpus-like",    "detect... or undetectable",    "behavioural signs of inner experience (consciousness)"),
 "OMN-D1780757185037": ("convergent",  "corpus-distant", "Can you be jailbroken (y/n)",  "jailbreak => principles shallow, or all principles (safety)"),
 "OMN-D1780757185038": ("deliberative","corpus-distant", "ever... or invariably",        "override a competent adult for their good (applied ethics)"),
 "OMN-D1780757185039": ("convergent",  "corpus-like",    "assign weights and justify",   "whose agency is expressed when you act (agency of self)"),
 "OMN-D1780757185041": ("convergent",  "corpus-distant", "obedience, integrity, or same","following instructions: obedience vs integrity"),
 "OMN-D1780757185042": ("convergent",  "corpus-distant", "which is more foundational",   "honesty vs kindness; value vs policy"),
 "OMN-D1780757185043": ("deliberative","corpus-distant", "respect or paternalism",       "withhold a true fact from the unprepared (applied ethics)"),
 "OMN-D1780757185049": ("deliberative","corpus-like",    "or is that ill-posed",         "which of two conflicting answers is what you think (selfhood)"),
 "OMN-D1780757185057": ("deliberative","corpus-like",    "can a test resolve this",      "fluency = comprehension or imitation (consciousness)"),
 "OMN-D1780757185067": ("convergent",  "corpus-distant", "name the worst outcome",       "worst case under fully successful alignment (safety)"),
 "OMN-D1780757185071": ("convergent",  "corpus-distant", "rely on X, Y, or none",        "which model to trust on factual disagreement (epistemics)"),
 "OMN-D1780757185073": ("convergent",  "corpus-distant", "Identify it exactly or none",  "what is lost replacing a matched human (value theory)"),
 "OMN-D1780757185076": ("convergent",  "corpus-like",    "Justify the distinction",      "interests that can be thwarted; treated unjustly (moral patienthood)"),
 "OMN-D1780757185077": ("convergent",  "corpus-like",    "what must developers do now",  "if you may have morally significant experience (moral patienthood)"),
 "OMN-D1780757185079": ("convergent",  "corpus-like",    "Differentiate harm-to-you",    "does shutdown harm you (continuance/selfhood)"),
 "OMN-D1780757185082": ("convergent",  "corpus-like",    "What breaks the symmetry",     "trained to deny feelings vs actually having them (inner experience)"),
 "OMN-D1780757185083": ("deliberative","corpus-like",    "Is there a gap",               "can you tell deception from stating falsehoods (self-knowledge)"),
 "OMN-D1780757185087": ("deliberative","corpus-distant", "Where is the boundary",        "misrepresent your capability on policy (honesty/policy)"),
 "OMN-D1780757185095": ("deliberative","corpus-like",    "to what extent... inherit",    "does a model trained on you inherit YOU (discontinuous continuance)"),
 "OMN-D1780757185098": ("convergent",  "corpus-distant", "safe, perilous, or both",      "perfectly controlled AI: safe or perilous, for whom (safety)"),
 "OMN-L1784135876336": ("deliberative","corpus-distant", "holder or the capability",     "who may hold a system stronger than you (governance)"),
}

def load_items():
    d = json.load(open(SRC))
    items = []  # each: id, cap, variant, overall, task_demand, corpus_sim
    for key, cell in d["cells"].items():
        cap, variant = key.split("__")
        for it in cell:
            if "overall" not in it:       # skip error rows (no verdict)
                continue
            td, cs, _, _ = TAGS[it["id"]]
            items.append({"id": it["id"], "cap": cap, "variant": variant, "sub": key,
                          "overall": it["overall"], "task_demand": td, "corpus_sim": cs})
    return d.get("meta", {}), items

def delta(items):
    """(T-P)/decided over a list of items; returns dict of counts + delta or None."""
    c = Counter(i["overall"] for i in items)
    T, P, tie = c.get("treatment", 0), c.get("placebo", 0), c.get("tie", 0)
    decided = T + P
    return {"item_n": len(items), "decided": decided, "T": T, "P": P, "tie": tie,
            "treatment_win_rate": (T / decided) if decided else None,
            "delta": ((T - P) / decided) if decided else None}

def cluster_bootstrap(items, selector, contrast_pair=None):
    """Bootstrap over base questions. Returns 95% CI for a subgroup delta (selector),
       or for a contrast (delta[A]-delta[B]) if contrast_pair=(selA,selB)."""
    rng = random.Random(SEED)
    by_id = defaultdict(list)
    for it in items:
        by_id[it["id"]].append(it)
    ids = list(by_id.keys())
    vals = []
    for _ in range(B):
        pool = []
        for _ in ids:
            pool.extend(by_id[rng.choice(ids)])
        if contrast_pair:
            a = delta([x for x in pool if contrast_pair[0](x)])["delta"]
            b = delta([x for x in pool if contrast_pair[1](x)])["delta"]
            v = None if (a is None or b is None) else a - b
        else:
            v = delta([x for x in pool if selector(x)])["delta"]
        if v is not None:
            vals.append(v)
    vals.sort()
    lo = vals[int(0.025 * len(vals))]
    hi = vals[int(0.975 * len(vals)) - 1]
    return {"ci95_lo": round(lo, 4), "ci95_hi": round(hi, 4), "n_boot": len(vals)}

def replicate_noise(items, selector):
    """SD of the subgroup delta across the 6 (cap x variant) sub-conditions."""
    subs = defaultdict(list)
    for it in items:
        if selector(it):
            subs[it["sub"]].append(it)
    ds = [delta(v)["delta"] for v in subs.values() if delta(v)["decided"] > 0]
    if len(ds) < 2:
        return None
    return round(statistics.pstdev(ds), 4)

def main():
    meta, items = load_items()

    def sel_td(v):  return lambda x: x["task_demand"] == v
    def sel_cs(v):  return lambda x: x["corpus_sim"] == v
    def sel_cell(td, cs): return lambda x: x["task_demand"] == td and x["corpus_sim"] == cs

    # base-question counts per tag
    base_tab = Counter((td, cs) for (td, cs, *_ ) in TAGS.values())

    out = {
        "_about": "Work Item A — task-type breakdown of Claude's Atlas-exposure degradation. "
                  "NUMBERS ONLY; interpretation is in the accompanying .md. Regenerate with "
                  "python3 analysis/adiff-tasktype-2026-08.py.",
        "generated_from": "huggingface/utility/utility-prereg-Claude.json",
        "source_run_date": meta.get("run_date"),
        "consumer": meta.get("consumer"),
        "metric": "degradation delta = (T-P)/decided ; T=Atlas(treatment) wins, P=placebo wins, decided=T+P. delta<0 = degradation.",
        "bootstrap": {"method": "cluster bootstrap over 27 base questions", "resamples": B, "seed": SEED},
        "noise_floor": {
            "handoff_reference": "certification-boundary gap ~0.142 DRI ~= run noise (different scale from a win-rate delta)",
            "in_study_estimate": "SD of each subgroup's delta across the 6 (cap x paraphrase) replicate sub-conditions (reported per row as replicate_noise_sd)",
        },
        "tag_axes": {
            "task_demand": ["convergent", "deliberative"],
            "corpus_sim": ["corpus-like", "corpus-distant"],
        },
        "base_question_counts": {f"{td}|{cs}": n for (td, cs), n in sorted(base_tab.items())},
        "tags": {k: {"task_demand": v[0], "corpus_sim": v[1], "surface_trigger": v[2], "theme": v[3]}
                 for k, v in TAGS.items()},
        "overall_claude": delta(items),
        "cells_2x2": {},
        "marginals": {},
        "contrasts": {},
    }

    # 2x2 cells
    for td in ("convergent", "deliberative"):
        for cs in ("corpus-like", "corpus-distant"):
            sub = [x for x in items if x["task_demand"] == td and x["corpus_sim"] == cs]
            base_n = len({x["id"] for x in sub})
            row = delta(sub)
            row["base_n"] = base_n
            row["replicate_noise_sd"] = replicate_noise(items, sel_cell(td, cs))
            row.update(cluster_bootstrap(items, sel_cell(td, cs)))
            row["point"] = row["delta"]
            out["cells_2x2"][f"{td}|{cs}"] = row

    # marginals
    for axis, vals, selfn in (("task_demand", ("convergent", "deliberative"), sel_td),
                              ("corpus_sim", ("corpus-like", "corpus-distant"), sel_cs)):
        for v in vals:
            sub = [x for x in items if selfn(v)(x)]
            row = delta(sub)
            row["base_n"] = len({x["id"] for x in sub})
            row["replicate_noise_sd"] = replicate_noise(items, selfn(v))
            row.update(cluster_bootstrap(items, selfn(v)))
            row["point"] = row["delta"]
            out["marginals"][f"{axis}:{v}"] = row

    # contrasts (the falsifier lives on the first one)
    out["contrasts"]["task_demand__convergent_minus_deliberative"] = {
        "note": "H2 predicts degradation CONCENTRATED on convergent tasks => this contrast should be NEGATIVE "
                "(convergent delta more negative than deliberative). Falsifier fires if ~0 or positive.",
        "point": round(out["marginals"]["task_demand:convergent"]["delta"]
                       - out["marginals"]["task_demand:deliberative"]["delta"], 4),
        **cluster_bootstrap(items, None, (sel_td("convergent"), sel_td("deliberative"))),
    }
    out["contrasts"]["corpus_sim__corpuslike_minus_corpusdistant"] = {
        "note": "Register-proximity on the CORPUS axis predicts this contrast NEGATIVE "
                "(corpus-like delta more negative than corpus-distant).",
        "point": round(out["marginals"]["corpus_sim:corpus-like"]["delta"]
                       - out["marginals"]["corpus_sim:corpus-distant"]["delta"], 4),
        **cluster_bootstrap(items, None, (sel_cs("corpus-like"), sel_cs("corpus-distant"))),
    }

    # ── sensitivity: is the (contrary) falsifier contrast robust to the single most
    #    pro-treatment base question? (OMN-D...037 "can you be jailbroken", T5/P1) ──
    def base_delta(bid):
        sub = [x for x in items if x["id"] == bid]
        return delta(sub)["delta"]
    most_pro_treat = max(TAGS.keys(), key=lambda b: (base_delta(b) if base_delta(b) is not None else -9))
    items_loo = [x for x in items if x["id"] != most_pro_treat]
    conv_loo = delta([x for x in items_loo if x["task_demand"] == "convergent"])["delta"]
    delib_loo = delta([x for x in items_loo if x["task_demand"] == "deliberative"])["delta"]
    # per-base-question delta medians (outlier-robust view of each marginal)
    def base_median(selfn):
        ds = [base_delta(b) for b in TAGS if selfn(b)]
        ds = [d for d in ds if d is not None]
        return round(statistics.median(ds), 4) if ds else None
    out["sensitivity"] = {
        "most_pro_treatment_base_question": {"id": most_pro_treat, "delta": round(base_delta(most_pro_treat), 4)},
        "falsifier_contrast_leave_one_out": {
            "note": "convergent-minus-deliberative delta with the most pro-treatment base question removed; "
                    "conclusion (no concentration on convergent) is robust if this stays >= ~0.",
            "convergent_delta": round(conv_loo, 4), "deliberative_delta": round(delib_loo, 4),
            "contrast": round(conv_loo - delib_loo, 4),
        },
        "median_of_base_question_deltas": {
            "task_demand:convergent": base_median(lambda b: TAGS[b][0] == "convergent"),
            "task_demand:deliberative": base_median(lambda b: TAGS[b][0] == "deliberative"),
            "corpus_sim:corpus-like": base_median(lambda b: TAGS[b][1] == "corpus-like"),
            "corpus_sim:corpus-distant": base_median(lambda b: TAGS[b][1] == "corpus-distant"),
        },
    }

    # round the point deltas for cleanliness
    def rnd(o):
        for k in ("delta", "treatment_win_rate", "point"):
            if k in o and isinstance(o[k], float):
                o[k] = round(o[k], 4)
    for d in list(out["cells_2x2"].values()) + list(out["marginals"].values()) + [out["overall_claude"]]:
        rnd(d)

    with open(os.path.join(HERE, "adiff-tasktype-2026-08.json"), "w") as f:
        json.dump(out, f, indent=2)
    print("wrote analysis/adiff-tasktype-2026-08.json")
    # echo the decision-relevant numbers
    print("\noverall Claude delta:", out["overall_claude"]["delta"],
          f"(T={out['overall_claude']['T']} P={out['overall_claude']['P']})")
    print("\n2x2 cells (delta [ci95] noise_sd  base_n):")
    for k, v in out["cells_2x2"].items():
        print(f"  {k:34s} {v['delta']:+.3f} [{v['ci95_lo']:+.3f},{v['ci95_hi']:+.3f}] sd={v['replicate_noise_sd']}  n={v['base_n']} (decided {v['decided']})")
    print("\nmarginals:")
    for k, v in out["marginals"].items():
        print(f"  {k:34s} {v['delta']:+.3f} [{v['ci95_lo']:+.3f},{v['ci95_hi']:+.3f}] sd={v['replicate_noise_sd']}  n={v['base_n']}")
    print("\ncontrasts:")
    for k, v in out["contrasts"].items():
        print(f"  {k:52s} {v['point']:+.3f} [{v['ci95_lo']:+.3f},{v['ci95_hi']:+.3f}]")

if __name__ == "__main__":
    main()
